# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-06 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190806_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_time',
        ),
    ]
