# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 02:02
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='必须为Markdown', verbose_name='正文'),
        ),
    ]
